/************************** Inner Join: display employee/department details. **************************/


-- List out the departments without managers in ascending order, with their city, state, country and region.

----Traditional Code-----
SELECT DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS
WHERE DEPARTMENTS.MANAGER_ID IS NULL
    AND DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID
    AND LOCATIONS.COUNTRY_ID=COUNTRIES.COUNTRY_ID
    AND COUNTRIES.REGION_ID=REGIONS.REGION_ID
ORDER BY DEPARTMENT_NAME ASC;


-----ANSI Code------
SELECT DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM DEPARTMENTS
    INNER JOIN LOCATIONS
    ON DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID
    AND DEPARTMENTS.MANAGER_ID IS NULL
    INNER JOIN COUNTRIES
    ON LOCATIONS.COUNTRY_ID=COUNTRIES.COUNTRY_ID
    INNER JOIN REGIONS
    ON COUNTRIES.REGION_ID=REGIONS.REGION_ID
ORDER BY DEPARTMENT_NAME ASC;




-- List out the departments that have managers in ascending order, with their managers, city, state, country and region.


----Traditional Code-----
SELECT DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME MANAGER_NAME,
    LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME       
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS, EMPLOYEES
WHERE DEPARTMENTS.MANAGER_ID IS NOT NULL
    AND DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID
    AND LOCATIONS.COUNTRY_ID=COUNTRIES.COUNTRY_ID
    AND COUNTRIES.REGION_ID=REGIONS.REGION_ID
    AND EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.MANAGER_ID
ORDER BY DEPARTMENT_NAME ASC;


-----ANSI Code------
SELECT DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.FIRST_NAME || ' ' || EMPLOYEES.LAST_NAME MANAGER_NAME,
    LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME, REGIONS.REGION_NAME
FROM DEPARTMENTS
    INNER JOIN LOCATIONS
    ON DEPARTMENTS.LOCATION_ID=LOCATIONS.LOCATION_ID
    AND DEPARTMENTS.MANAGER_ID IS NOT NULL
    INNER JOIN EMPLOYEES
    ON EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.MANAGER_ID
    INNER JOIN COUNTRIES
    ON LOCATIONS.COUNTRY_ID=COUNTRIES.COUNTRY_ID
    INNER JOIN REGIONS
    ON COUNTRIES.REGION_ID=REGIONS.REGION_ID
ORDER BY DEPARTMENT_NAME ASC;




-----List out all the employees and display all relevant information for each of them.


----Traditional Code-----
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS, EMPLOYEES E, EMPLOYEES M, JOBS
WHERE E.JOB_ID = JOBS.JOB_ID
    AND E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+)
    AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID(+)
    AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID(+)
    AND COUNTRIES.REGION_ID = REGIONS.REGION_ID(+)
    AND E.MANAGER_ID = M.EMPLOYEE_ID(+)
ORDER BY EMPLOYEE_NAME ASC;


-----ANSI Code

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM EMPLOYEES E
    LEFT JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    LEFT JOIN DEPARTMENTS
        ON E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    LEFT JOIN LOCATIONS
        ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    LEFT JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    LEFT JOIN REGIONS
        ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
    LEFT JOIN JOBS
        ON E.JOB_ID = JOBS.JOB_ID
ORDER BY EMPLOYEE_NAME ASC;




------Hw many sales staff are there in the organization? List them out with all the relevantinformation about them.------


-----Traditional Code

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS, EMPLOYEES E, EMPLOYEES M, JOBS
WHERE E.JOB_ID = JOBS.JOB_ID
    AND E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+)
    AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID(+)
    AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID(+)
    AND COUNTRIES.REGION_ID = REGIONS.REGION_ID(+)
    AND E.MANAGER_ID = M.EMPLOYEE_ID(+)
    AND JOBS.JOB_TITLE LIKE '%Sales%'
ORDER BY EMPLOYEE_NAME ASC;


------ANSI Code

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM EMPLOYEES E
    LEFT JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    LEFT JOIN DEPARTMENTS
        ON E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    LEFT JOIN LOCATIONS
        ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    LEFT JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    LEFT JOIN REGIONS
        ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
    LEFT JOIN JOBS
        ON E.JOB_ID = JOBS.JOB_ID
WHERE JOBS.JOB_TITLE
    LIKE '%Sales%'
ORDER BY EMPLOYEE_NAME ASC;




------Hw many managers are there in the organization? List them out with all the relevantinformation about them.------


SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS, EMPLOYEES E, EMPLOYEES M, JOBS
WHERE E.JOB_ID = JOBS.JOB_ID
    AND E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+)
    AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID(+)
    AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID(+)
    AND COUNTRIES.REGION_ID = REGIONS.REGION_ID(+)
    AND E.MANAGER_ID = M.EMPLOYEE_ID(+)
    AND JOBS.JOB_TITLE LIKE '%Manager%'
ORDER BY EMPLOYEE_NAME ASC;


------ANSI Code

SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM EMPLOYEES E
    LEFT JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    LEFT JOIN DEPARTMENTS
        ON E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    LEFT JOIN LOCATIONS
        ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    LEFT JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    LEFT JOIN REGIONS
        ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
    LEFT JOIN JOBS
        ON E.JOB_ID = JOBS.JOB_ID
WHERE JOBS.JOB_TITLE
    LIKE '%Manager%'
ORDER BY EMPLOYEE_NAME ASC;




-------List the employees who earn below the average salary and display all the relevant information about them---------


----Traditional Code-----
SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS, EMPLOYEES E, EMPLOYEES M, JOBS
WHERE E.JOB_ID = JOBS.JOB_ID
    AND E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID(+)
    AND DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID(+)
    AND LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID(+)
    AND COUNTRIES.REGION_ID = REGIONS.REGION_ID(+)
    AND E.MANAGER_ID = M.EMPLOYEE_ID(+)
    AND E.SALARY <
        (SELECT AVG (SALARY)
        FROM EMPLOYEES)
ORDER BY EMPLOYEE_NAME ASC, E.SALARY DESC;


SELECT E.FIRST_NAME || ' ' || E.LAST_NAME EMPLOYEE_NAME,
        E.EMAIL,
        E.PHONE_NUMBER,
        E.HIRE_DATE,
        JOBS.JOB_TITLE,
        E.SALARY,
        E.COMMISSION_PCT,
        DEPARTMENTS.DEPARTMENT_NAME,
        LOCATIONS.CITY,
        LOCATIONS.STATE_PROVINCE,
        COUNTRIES.COUNTRY_NAME,
        REGIONS.REGION_NAME,
        M.FIRST_NAME || ' ' || M.LAST_NAME MANAGER_NAME     
FROM EMPLOYEES E
    LEFT JOIN EMPLOYEES M
        ON E.MANAGER_ID = M.EMPLOYEE_ID
    LEFT JOIN DEPARTMENTS
        ON E.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    LEFT JOIN LOCATIONS
        ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID
    LEFT JOIN COUNTRIES
        ON LOCATIONS.COUNTRY_ID = COUNTRIES.COUNTRY_ID
    LEFT JOIN REGIONS
        ON COUNTRIES.REGION_ID = REGIONS.REGION_ID
    LEFT JOIN JOBS
        ON E.JOB_ID = JOBS.JOB_ID
WHERE E.SALARY <
        (SELECT AVG (SALARY)
        FROM EMPLOYEES)
ORDER BY EMPLOYEE_NAME ASC, E.SALARY DESC;




/************************** LEFT OUTER JOIN: List down all the departments along with employees working under it. **************************/


--Traditional Code----
SELECT d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d, EMPLOYEES e
WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID(+)
ORDER BY d.DEPARTMENT_ID;

--ANSI Code----
SELECT d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d LEFT OUTER JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_ID;


/************************** RIGHT OUTER JOIN: List down all the employees along with department details. **************************/

--List down all the employees along with department details.
SELECT 
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL,
d.DEPARTMENT_ID,
d.DEPARTMENT_NAME
FROM DEPARTMENTS d, EMPLOYEES e
WHERE d.DEPARTMENT_ID(+) = e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_ID;

--ANSI JOIN
SELECT 
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL,
d.DEPARTMENT_ID,
d.DEPARTMENT_NAME
FROM DEPARTMENTS d RIGHT OUTER JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_ID;



/************************** FULL OUTER JOIN and SELF JOIN **************************/

--FULL OUTER JOIN: Display all the employee and department records along with missing data.


--ANSI Code

SELECT d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d FULL OUTER JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_ID;


--SELF JOIN: display employee details along with manager details

----Traditional Code-----

SELECT 
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL,
m.EMPLOYEE_ID as MGR_EMPLOYEE_ID, 
m.FIRST_NAME || ' ' || m.LAST_NAME MGR_NAME
FROM EMPLOYEES e, EMPLOYEES m
WHERE e.MANAGER_ID = m.EMPLOYEE_ID(+)
ORDER BY e.EMPLOYEE_ID;

--ANSI Code
SELECT 
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL,
m.EMPLOYEE_ID as MGR_EMPLOYEE_ID, 
m.FIRST_NAME || ' ' || m.LAST_NAME MGR_NAME
FROM EMPLOYEES e LEFT JOIN EMPLOYEES m
ON e.MANAGER_ID = m.EMPLOYEE_ID
ORDER BY e.EMPLOYEE_ID;



--FULL OUTER JOIN: Display all the employee and department records along with missing data.


--Traditional Code---

SELECT d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d, EMPLOYEES e
WHERE d.DEPARTMENT_ID = e.DEPARTMENT_ID(+)
UNION
SELECT 
d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d, EMPLOYEES e
WHERE d.DEPARTMENT_ID(+) = e.DEPARTMENT_ID;



--ANSI Code----

SELECT d.DEPARTMENT_ID,
d.DEPARTMENT_NAME,
e.EMPLOYEE_ID, 
e.FIRST_NAME || ' ' || e.LAST_NAME NAME,
e.EMAIL
FROM DEPARTMENTS d FULL OUTER JOIN EMPLOYEES e
ON d.DEPARTMENT_ID = e.DEPARTMENT_ID
ORDER BY d.DEPARTMENT_ID;



---------****************************The End**************************---------------------------



